//==================================================
// This file contains the Excluded objects
// Generated By User: wwh
// Format Version: 2
// Date: Mon Jun 29 16:19:29 2026
// ExclMode: default
//==================================================
CHECKSUM: "238962367 3920802815"
INSTANCE: tb_top.dut.u_spi_ctrl
Block 39 "1707670903" "state_q <= SPI_ST_IDLE;"
CHECKSUM: "238962367 2990646480"
INSTANCE: tb_top.dut.u_spi_ctrl
Condition 1 "717173289" "(cfg_enable && cfg_tx_en && tx_fifo_empty) 1 -1" (3 "110")
Condition 2 "4036716184" "(cfg_cont && cfg_enable && cfg_tx_en && ((!tx_fifo_empty))) 1 -1" (2 "1011")
Condition 14 "626485653" "(cs_active_q || (state_q == SPI_ST_FRAME_DONE)) 1 -1" (2 "01")
CHECKSUM: "238962367 3393187855"
INSTANCE: tb_top.dut.u_spi_ctrl
Branch 5 "4048521225" "(!rst_n)" (21) "(!rst_n) 0,0,default,-,-,-,-,-,-,-,-,-,-,-,-"
CHECKSUM: "237798123 2491642910"
INSTANCE: tb_top.dut.u_tx_fifo
Condition 2 "2917028794" "(r_en && ((!empty))) 1 -1" (2 "10")
CHECKSUM: "237798123 2491642910"
INSTANCE: tb_top.dut.u_rx_fifo
Condition 1 "3974653964" "(w_en && ((!full))) 1 -1" (2 "10")
CHECKSUM: "2900447622 2221788054"
INSTANCE: tb_top.dut.u_apb_reg_block
Toggle paddr "logic paddr[11:0]"
Toggle pready "logic pready"
Toggle addr_dec "logic addr_dec[11:0]"
CHECKSUM: "625928845 3822643414"
INSTANCE: tb_top.dut.u_apb_protocol_sva
Toggle PADDR "logic PADDR[11:0]"
Toggle PREADY "logic PREADY"
