//==================================================
// This file contains the Excluded objects
// Generated By User: wwh
// Format Version: 2
// Date: Mon Jun 29 11:56:38 2026
// ExclMode: default
//==================================================
CHECKSUM: "237798123 2491642910"
INSTANCE: tb_top.dut.u_rx_fifo
Condition 1 "3974653964" "(w_en && ((!full))) 1 -1" (2 "10")
CHECKSUM: "237798123 2491642910"
INSTANCE: tb_top.dut.u_tx_fifo
Condition 2 "2917028794" "(r_en && ((!empty))) 1 -1" (2 "10")
CHECKSUM: "238962367 2990646480"
INSTANCE: tb_top.dut.u_spi_ctrl
Condition 2 "4036716184" "(cfg_cont && cfg_enable && cfg_tx_en && ((!tx_fifo_empty))) 1 -1" (2 "1011")
